services:
  backend:
    build:
      context: backend
    ports:
      - "12300:12300"
    environment:
      - DEV_MODE=${DEV_MODE:-true}
    command: sh -c 'fastapi $${DEV_MODE:+dev} main.py'
    volumes:
      - ./backend:/app

  internal_api:
    build:
      context: internal_api
    ports:
      - "12301:12301"
    environment:
      - DEV_MODE=${DEV_MODE:-true}
    command: sh -c 'fastapi $${DEV_MODE:+dev} main.py'
    volumes:
      - ./internal_api:/app

  db:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
