services:
  frontend:
    build:
      context: frontend
    ports:
      - "12300:12300"
    command: npm run dev
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend

  backend:
    build:
      context: backend
    ports:
      - "12301:12301"
    command: fastapi dev --host 0.0.0.0 --port 12301 main.py
    depends_on:
      - db
      - internal_api
    volumes:
      - ./backend:/backend

  internal_api:
    build:
      context: internal_api
    ports:
      - "12302:12302"
    command: fastapi dev --host 0.0.0.0 --port 12302 main.py
    volumes:
      - ./internal_api:/app

# if i delete the containers there appears to be a race condition where backend
# fails to start because the db container isn't ready yet
  db:
    image: postgres:17.1
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
