services:
  backend:
    build:
      context: backend
    ports:
      - "12300:12300"
    environment:
      - DEV_MODE=${DEV_MODE:-true}
    command: sh -c 'fastapi $${DEV_MODE:+dev} --host 0.0.0.0 --port 12300 main.py'
    depends_on:
      - db
      - internal_api
    volumes:
      - ./backend:/backend

  internal_api:
    build:
      context: internal_api
    ports:
      - "12301:12301"
    environment:
      - DEV_MODE=${DEV_MODE:-true}
    command: sh -c 'fastapi $${DEV_MODE:+dev} --host 0.0.0.0 --port 12301 main.py'
    volumes:
      - ./internal_api:/app

# if i delete the containers there appears to be a race condition where backend
# fails to start because the db container isn't ready yet
  db:
    image: postgres:17.1
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
