services:
  frontend:
    build:
      context: frontend
    ports:
      - "12300:12300"
    command: >
      sh -c "npm install --production=false &&
             npm run dev"
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend

  backend:
    build:
      context: backend
    ports:
      - "12301:12301"
    command: fastapi dev --host 0.0.0.0 --port 12301 main.py
    depends_on:
      db:
        condition: service_healthy
      internal_api:
        condition: service_started
    volumes:
      - ./backend:/backend

  internal_api:
    build:
      context: internal_api
    ports:
      - "12302:12302"
    command: fastapi dev --host 0.0.0.0 --port 12302 main.py
    volumes:
      - ./internal_api:/app

  db:
    image: postgres:17.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
