version: "3.7"

services:
  db:
    restart: always
    image: mysql:8.0.26
    secrets:
      - db-password
    environment:
      - MYSQL_DATABASE=appsecdb
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  web:
    restart: always
    build: 
      context: ./webapp
    expose:
      - 8000
    command: [ "/usr/local/bin/gunicorn", "--log-level=debug", "-w", "3", "-b", ":8000", "wsgi" ]
    env_file: ./webapp/.env
    secrets:
      - db-password
    networks:
      - frontend
      - backend

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    volumes:
      - /etc/keys/:/etc/keys/

volumes:
  db-data:
secrets:
  db-password:
    file: ./webapp/dbpwd.txt
networks:
  frontend:
  backend:
