version: "3.9"

services:
  web:
    container_name: web
    build: 
      context: ./webapp
    expose:
      - "8000"
    command: /usr/local/bin/gunicorn -w 3 -b :8000 wsgi
    env_file: ./webapp/.env
    volumes:
      - ./webapp/:/app

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
