services:
  web:
    build:
      context: ./webapp
    ports:
      - "12300:12300"
    environment:
      FLASK_ENV: "development"
      FLASK_DEBUG: "true"
      FLASK_APP: "wsgi.py"
      SECRET_KEY: "test"
    command: [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=12300" ]
    volumes:
      - ./webapp/:/app

  internal_api:
    build:
      context: ./ssrf/internal_api
    environment:
      FLASK_ENV: "development"
      FLASK_APP: "wsgi.py"
    command: [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=12301" ]
    volumes:
      - ./ssrf/internal_api/:/app

  open_redirect:
    build:
      context: ./webapp/webapp/tests/open_redirect
    ports:
      - "12302:12302"
    environment:
      FLASK_ENV: "development"
      FLASK_APP: "index.py"
    command: [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=12302" ]
    volumes:
      - ./webapp/webapp/tests/open_redirect/:/app

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "appsecdb"
      MYSQL_ROOT_PASSWORD: "test"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log

