version: "3.9"

services:
  web:
    build:
      context: ./webapp
    ports:
      - 5000:5000
    secrets:
      - db-password
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - FLASK_APP=wsgi.py
      - SECRET_KEY=test
    command: [ "python3", "-m" , "flask", "run", "--host=0.0.0.0" ]
    volumes:
      - ./webapp/:/app

  db:
    image: mysql:8.0.23
    secrets:
      - db-password
    environment:
      - MYSQL_DATABASE=appsecdb
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
secrets:
  db-password:
    file: ./webapp/dbpwd.txt
